# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7e83e51cdb95acbbabfacab6589562d9bb8dc914e52e43b1c52534c3b2faf7f9cc4dd41e4b070cded8e539e46d134ed0b4bb630c056722d7d5fc0f0c7f82470

test:
  secret_key_base: 986b72bc3d3330d04509a37fbc738b57c4bb77ef18ad011b07f84c05a709e06e215b075a1d31d2c2449e7a3d9f9f10bd327a3d9fb56b61f7c2f47336817ffeae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
